name: Android CI

on:
  push:
    branches:
      - media_scan
      - dev
      - master
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      SPLITS_INCLUDE: "TRUE"

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Decode and Save Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/keystore.jks
          chmod 600 $GITHUB_WORKSPACE/keystore.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Signed APKs
        run: ./gradlew assembleRelease

      - name: Upload APKs to GitHub Artifacts
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: apk-files
          path: app/build/outputs/apk/release/*.apk

  release:
    name: Release APKs
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download APKs from build
        uses: actions/download-artifact@v4
        with:
          name: apk-files
          path: apk-release

      - name: Upload Release APKs
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GH_PAT }}
          prerelease: false
          body: "Autogenerated release for F-Droid autobuild"
          draft: false
          make_latest: true
          tag_name: ${{ github.ref_name }}
          files: apk-release/*.apk
